# Five fingertip views and a third view, with fingertip poses and currents.
defaults:
  - base
  - _self_

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    camera1_rgb: # Thumb
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False
    camera2_rgb: # Index
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False
    camera3_rgb: # Middle
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False
    camera4_rgb: # Ring
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False
    camera5_rgb: # Little finger
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False

    tv_rgb: # Third view
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False

    joint_pos:
      shape: [26] # 6 arm joints followed by 20 hand joints
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
    finger_cur:
      shape: [5, 4] # Selected fingers, 4 joints each
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
    camera_pos:
      shape: [5, 3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
    camera_ori:
      shape: [5, 6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
  action:
    shape: [26]
    horizon: ${task.action_horizon}
    latency_steps: 0
    down_sample_steps: ${task.obs_down_sample_steps}
